# Generated by Django 2.1.15 on 2020-12-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ciudad',
            field=models.CharField(default=1, max_length=100, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='departamento',
            field=models.CharField(blank=True, max_length=2, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dirreccion',
            field=models.CharField(default=1, max_length=150, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='piso',
            field=models.IntegerField(blank=True, default=1, verbose_name='Piso'),
            preserve_default=False,
        ),
    ]
