# Generated by Django 2.1.15 on 2020-12-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20201230_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='antecedentes',
            field=models.TextField(default=1, verbose_name='Antecedentes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='codigo_postal',
            field=models.CharField(default=1, max_length=8, verbose_name='Codigo_Postal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='mail',
            field=models.CharField(default=1, max_length=100, verbose_name='Mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='motivo',
            field=models.TextField(default=1, verbose_name='Motivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='telefono',
            field=models.CharField(default=1, max_length=15, verbose_name='Telefono'),
            preserve_default=False,
        ),
    ]
