# Generated by Django 2.1.15 on 2020-12-30 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20201230_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
