# Generated by Django 2.1.15 on 2020-12-30 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_auto_20201230_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.date(2020, 12, 30)),
        ),
    ]
