# Generated by Django 2.1.15 on 2020-12-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_auto_20201230_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fecha_modificacion',
        ),
    ]
