# Generated by Django 2.1.15 on 2020-12-30 04:07

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_auto_20201230_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 30), verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='patient',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de modificación'),
            preserve_default=False,
        ),
    ]
