# Generated by Django 2.1.15 on 2020-12-30 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_auto_20201230_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2020, 12, 30), verbose_name='Fecha de registro'),
        ),
    ]
