# Generated by Django 2.1.15 on 2020-12-30 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_auto_20201230_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 30, 1, 10, 1, 356513), verbose_name='Fecha de registro'),
        ),
    ]
