# Generated by Django 2.1.15 on 2020-12-30 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0011_auto_20201230_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2020, 12, 30, 1, 42, 34, 857152), verbose_name='Fecha de registro'),
        ),
    ]
