# Generated by Django 2.1.15 on 2020-12-31 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0012_auto_20201230_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='departamento',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2020, 12, 30, 21, 53, 15, 540376), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='piso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Piso'),
        ),
    ]
