# Generated by Django 2.1.15 on 2020-12-31 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0013_auto_20201230_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2020, 12, 31, 2, 40, 15, 508587), verbose_name='Fecha de registro'),
        ),
    ]
