# Generated by Django 2.1.15 on 2020-12-31 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0016_auto_20201231_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='retinografia_left',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Retinografia izquierda'),
        ),
        migrations.AddField(
            model_name='patient',
            name='retinografia_rigth',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Retinografia derecha'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2020, 12, 31, 3, 56, 31, 9228), verbose_name='Fecha de registro'),
        ),
    ]
