# Generated by Django 2.1.15 on 2021-02-06 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0018_auto_20210103_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2021, 2, 6, 0, 6, 3, 692763), editable=False, verbose_name='Fecha de registro'),
        ),
    ]
