# Generated by Django 2.1 on 2021-04-14 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0020_auto_20210218_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 18, 29, 0, 873019), editable=False, verbose_name='Fecha de registro'),
        ),
    ]
