# Generated by Django 2.1 on 2021-04-14 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0021_auto_20210414_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de registro'),
        ),
    ]
